@startuml

[*] --> 初期状態
初期状態 : 1~6 or 0 の入力待ち

'人の登録
初期状態 --> 人登録 : 1

人登録 : 名前の入力待ち
人登録 --> 名前の確認 : 任意の文字列

名前の確認 : 1/0 の入力待ち
名前の確認 -up-> 初期状態 : 1/0


'人削除
初期状態 --> 人削除 : 2

人削除 : 0~9 の入力待ち
人削除 --> 人削除 : 1/2
人削除 --> 人削除確認 : 3~9
人削除 -up-> 初期状態 : 0

人削除確認 : 1/0 の入力待ち
人削除確認 -up-> 初期状態 : 1-成功
人削除確認 -up-> 人削除 : 0/1-失敗


'予定登録
初期状態 --> 予定登録 : 3 

予定登録 : 1/2/0 の入力待ち
予定登録 --> 予定の新規登録 : 1
予定登録 --> 予定の提案 : 2
予定登録 -up-> 初期状態 : 0

予定の新規登録 : 1~4 or 9/0 の入力待ち
予定の新規登録 --> 予定の情報入力 : 1~4
予定の新規登録 --> 予定確定 : 9
予定の新規登録 -up-> 予定登録 : 0

予定の情報入力 : 文字の入力待ち
予定の情報入力 -up-> 予定の新規登録 : 任意の文字列

予定確定 : 1/0 の入力待ち
予定確定 -up-> 初期状態 : 1-成功
予定確定 -up-> 予定の新規登録 : 0/1-失敗


予定の提案 : 1~6 or 9/0 の入力待ち
予定の提案 --> 予定の検索条件 : 1~6
予定の提案 --> 予定の新規登録 : 9-成功
予定の提案 --> 予定の提案 : 9-失敗
予定の提案 -up-> 予定登録 : 0

予定の検索条件 : 文字の入力待ち
予定の検索条件 -up-> 予定の提案 : 任意の文字列


'予定削除
初期状態 --> 予定削除 : 4

予定削除 : 0~9 の入力待ち
予定削除 --> 予定削除 : 1/2
予定削除 --> 予定削除確認 : 3~9
予定削除 -up-> 初期状態 : 0

予定削除確認 : 1/0 の入力待ち
予定削除確認 -up-> 初期状態 : 1-成功
予定削除確認 -up-> 予定削除 :0/1-失敗


'ファイル保存
初期状態 --> ファイルに保存 : 5

ファイルに保存 : 1/0 の入力待ち
ファイルに保存 -up-> 初期状態 : 1/0


'ファイル読込
初期状態 --> ファイルを読込 : 6

ファイルを読込 : 1/0 の入力待ち
ファイルを読込 -up-> 初期状態 : 1/0


初期状態 --> [*] : 0

@enduml